---
abstract: 'concatenate and print JSON files'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PipeFilter
requires:
  JSON::Path: 0
  JSON::XS: 0
  Moose: 0
  MooseX::Getopt: 0
  YAML::Any: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-PipeFilter
  repository: git://github.com/rcaputo/app-pipefilter.git
version: 0.005
